server:
  port: ${PORT:6969}
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        - id: FOOD-SERVICE
          uri: lb://FOOD-SERVICE
          predicates:
            - Path=/api/food/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    hostname: n5-subprj-food.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: https://n5-subprj-eurekaserver.herokuapp.com/eureka